/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.TrainerRole;
import backend.AdminRole;

/**
 *
 * @author ahmed-sameh
 */
public class TrainerOptions extends javax.swing.JFrame {

    public TrainerRole trainer = new TrainerRole();
    public AdminRole admin = new AdminRole();

    /**
     * Creates new form TrainerOptions
     */

    public TrainerOptions() {
        initComponents();
        this.setTitle("Trainer Role");
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMember = new javax.swing.JButton();
        viewMembers = new javax.swing.JButton();
        addClass = new javax.swing.JButton();
        viewClasses = new javax.swing.JButton();
        register = new javax.swing.JButton();
        cancelRegister = new javax.swing.JButton();
        viewRegisters = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addMember.setText("Add Member");
        addMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMemberActionPerformed(evt);
            }
        });

        viewMembers.setText("View Members ");
        viewMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMembersActionPerformed(evt);
            }
        });

        addClass.setText("Add Class");
        addClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClassActionPerformed(evt);
            }
        });

        viewClasses.setText("View Classes");
        viewClasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewClassesActionPerformed(evt);
            }
        });

        register.setText("Register Member For Class");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        cancelRegister.setText("Cancel Registration");
        cancelRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelRegisterActionPerformed(evt);
            }
        });

        viewRegisters.setText("View Registrations");
        viewRegisters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRegistersActionPerformed(evt);
            }
        });

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewMembers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewClasses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(register, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(cancelRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewRegisters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(addMember)
                .addGap(40, 40, 40)
                .addComponent(viewMembers)
                .addGap(48, 48, 48)
                .addComponent(addClass)
                .addGap(47, 47, 47)
                .addComponent(viewClasses)
                .addGap(52, 52, 52)
                .addComponent(register)
                .addGap(45, 45, 45)
                .addComponent(cancelRegister)
                .addGap(38, 38, 38)
                .addComponent(viewRegisters)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(logout)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMemberActionPerformed
        // TODO add your handling code here:
        addMember m = new addMember(trainer);
        m.setVisible(true);
    }//GEN-LAST:event_addMemberActionPerformed

    private void viewClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewClassesActionPerformed
        // TODO add your handling code here:
        ViewClasses vc = new ViewClasses(trainer);
        vc.setVisible(true);


    }//GEN-LAST:event_viewClassesActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        RegisterMember rm = new RegisterMember(trainer);
        rm.setVisible(true);
    }//GEN-LAST:event_registerActionPerformed

    private void cancelRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelRegisterActionPerformed
        // TODO add your handling code here:
        CancelRegistration cr = new CancelRegistration(trainer);
        cr.setVisible(true);
    }//GEN-LAST:event_cancelRegisterActionPerformed

    private void viewRegistersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRegistersActionPerformed
        // TODO add your handling code here:
        ViewRegistrations vr = new ViewRegistrations (trainer);
        vr.setVisible(true);
    }//GEN-LAST:event_viewRegistersActionPerformed

    private void viewMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMembersActionPerformed
        // TODO add your handling code here:
        ViewMembers vm = new ViewMembers(trainer);
        vm.setVisible(true);
    }//GEN-LAST:event_viewMembersActionPerformed

    private void addClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClassActionPerformed
        // TODO add your handling code here:
        AddClass addClassWindow = new AddClass(trainer, admin);
        addClassWindow.setVisible(true);
    }//GEN-LAST:event_addClassActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        trainer.logout();
        setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addClass;
    private javax.swing.JButton addMember;
    private javax.swing.JButton cancelRegister;
    private javax.swing.JButton logout;
    private javax.swing.JButton register;
    private javax.swing.JButton viewClasses;
    private javax.swing.JButton viewMembers;
    private javax.swing.JButton viewRegisters;
    // End of variables declaration//GEN-END:variables
}
